name: Update README

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *'

jobs: 
    update-readme-with-blog: 
        name: Update README with my latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "8"
                feed_list: "https://nitratine.net/rss.xml"

    update-readme-with-youtube:
        name: Update README with my latest videos on YouTube
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with:
                comment_tag_name: "YOUTUBE"
                feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCesEknt3SRX9R9W_f93Tb7g"

#     update-readme-images:
#         name: Generate new images for README
#         runs-on: ubuntu-latest
#         steps:
#             - uses: actions/checkout@v2
#             - uses: lowlighter/metrics@latest
#               with:
#                 token: ${{ secrets.METRICS_TOKEN }}
#                 committer_token: ${{ secrets.GITHUB_TOKEN }}
#                 filename: 'images/habbits.svg'
                
#                 base: "header, repositories"
#                 plugin_lines: yes
#                 plugin_traffic: yes
                
#                 plugin_habits: yes
#                 plugin_habits_from: 1000
#                 plugin_habits_days: 30
#                 plugin_habits_facts: no
#                 plugin_habits_charts: yes
#                 config_timezone: Pacific/Auckland
                
#                 plugin_languages: yes
#                 plugin_languages_skipped: 'Lucy-In-The-Sky-With-Emotion'
